### ISSUE TITLE
Metadata/options need conversion to JSON

### ISSUE THREAD

**Issue by schivmeister** [Vourhey/pinatapy#19]
After the last update to properly handle `options` data, providing `options.pinataMetadata` (and perhaps also `options.pinataOptions`) still error out.

Input:
```python
pinata_metadata = {"pinataMetadata": { "name": "A Test File" }}
pinata.pin_json_to_ipfs(file, options=pinata_metadata)
```

Output:
```
{'status': 400, 'reason': 'Bad Request', 'text': '{"error":"Invalid JSON provided"}'}
```

It appears providing the metadata body as a JSON string solves this.

```python
import json
metadata_content = { "name": "A Test File" }
pinata_metadata = {"pinataMetadata": json.dumps(metadata_content)}
pinata.pin_json_to_ipfs(file, options=pinata_metadata)
```

I am not sure if this should be done user-side, because this is not documented. And of course, thanks for this script!

**Comment by Smehnov** [comment]
Fixed in https://github.com/Vourhey/pinatapy/pull/20

**Comment by Vourhey** [comment]
PR #20 accepted
