### ISSUE TITLE
upload folder root path 

### ISSUE THREAD

**Issue by alexlatif** [Vourhey/pinatapy#21]
Thanks for the SDK, it works very well. When i give the path to the folder it looks something like

/Users/username/folder/

when i upload a folder manually it will resolve all files to be in root such that when i open the gateway url with my hash i get immediately the contents i am looking for.

the sdk is currently creating a folder structure where it takes a few layers to go from root hash to my contents.

this is important i believe as the merkle tree takes a longer time to build the more layers it has.

is there a way I can accomplish this? perhaps i am using your library incorrectly?

would greatly appreciate your help.

**Comment by Vourhey** [comment]
Hello @alexlatif 

Check out a new version 0.1.9 of the library

Basically it's the way Pinata works. If you want to upload a folder and `save_absolute_path = True`, then Pinata will upload the folder keeping the whole tree you provided. Otherwise it doesn't allow to upload multiple files into root.

**Comment by tubleronchik** [comment]
Hi @alexlatif

Starting from version 0.1.9, you can now pin a directory with `save_absolute_path = False`. If you do not specify a custom directory using the ipfs_destination_path parameter, the files will be pinned to the last common directory shared by all the files being pinned. For example, if you are pinning a directory located at /home/user/test-dir, the files will be pinned to the /test-dir directory.

**Comment by Vourhey** [comment]
Since there was no answer in a while, I'm closing the issue
