### ISSUE TITLE
Custom "API_ENDPOINT" 

### ISSUE THREAD

**Issue by ensrationis** [Vourhey/pinatapy#23]
Now we have only constant gateway: https://github.com/Vourhey/pinatapy/blob/master/pinatapy/__init__.py#L15

Pinata allows you to create custom gateways. Can we make it usable for library to prevent tons request to main point? 

![image](https://github.com/Vourhey/pinatapy/assets/14291169/9415fbd7-9d39-424a-9154-312fa67a4562)

**Comment by ensrationis** [comment]
Ans here is a motivation: 
`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='[api.pinata.cloud](http://api.pinata.cloud/)', port=443): Max retries exceeded with url: /pinning/unpin/QmQGez8qB...4ban3mzRm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1d...0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))`

Happens when I tried to del many files with @tubleronchik script

**Comment by tubleronchik** [comment]
Custom gateways allow only reading for now. Based on [docs](https://docs.pinata.cloud/reference/delete_pinning-unpin-cid) pins should be removed using main Pinata gateway.
