### ISSUE TITLE
How to avoid uploading folder path? 

### ISSUE THREAD

**Issue by chillingdino** [Vourhey/pinatapy#4]
Hello, 
i have tried using a folder but im sadly getting the entire /home/documents/ ecc. that i would like to "hide"
is there a way to avoid uploading the entire path of the folder?

thank you for this nice library

edit1: i tried changing to `res = requests.post(self.__endpoint + url_suffix, files=files, data/params = options,  headers=self.headers)` to pass `wrapWithDirectory = false` but im always the the same cid with same directory, i also tried on files["pinataOptions"] to add the wrapWithDirectory = false but always getting the same cid with the path

Edit2:

i manged to do it with:

`files = [("file",(str(pathlib.PurePath(file).parent.name + "/"+ pathlib.PurePath(file).name), open(file, "rb"))) for file in path_to_file.glob('*') if not file.is_dir()]`

**Comment by Vourhey** [comment]
Hey! To be honest I don't currently work on this repo. If you've figured out how to do it, please send me a PR. I'll be glad to accept it

**Comment by arseniiarsenii** [comment]
@bcvent I have submitted a PR which is likely to resolve your issue sunce this functionality has been reimplemented. You need however to wait for @Vourhey to merge it.

**Comment by Vourhey** [comment]
Merged
